package ovo.xsvf.transformers;

import ovo.xsvf.api.ITransformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.HashMap;
import java.util.Map;

public class BlockRenamingTransformer implements ITransformer {
    Map<String, String> renamePairs = new HashMap<>();
    {
        renamePairs.put("stone_granite.png", "granite.png");
        renamePairs.put("stone_granite_smooth.png", "polished_granite.png");
        renamePairs.put("stone_diorite.png", "diorite.png");
        renamePairs.put("stone_diorite_smooth.png", "polished_diorite.png");
        renamePairs.put("stone_andesite.png", "andesite.png");
        renamePairs.put("stone_andesite_smooth.png", "polished_andesite.png");
        renamePairs.put("grass_side.png", "grass_block_side.png");
        renamePairs.put("grass_top.png", "grass_block_top.png");
        renamePairs.put("dirt_podzol_side.png", "podzol_side.png");
        renamePairs.put("dirt_podzol_top.png", "podzol_top.png");
        renamePairs.put("planks_acacia.png", "acacia_planks.png");
        renamePairs.put("planks_big_oak.png", "dark_oak_planks.png");
        renamePairs.put("planks_birch.png", "birch_planks.png");
        renamePairs.put("planks_jungle.png", "jungle_planks.png");
        renamePairs.put("planks_spruce.png", "spruce_planks.png");
        renamePairs.put("planks_oak.png", "oak_planks.png");
        renamePairs.put("quartz_ore.png", "nether_quartz_ore.png");
        renamePairs.put("sponge_wet.png", "wet_sponge.png");
        renamePairs.put("sandstone_normal.png", "sandstone.png");
        renamePairs.put("sandstone_carved.png", "chiseled_sandstone.png");
        renamePairs.put("sandstone_smooth.png", "cut_sandstone.png");
        renamePairs.put("red_sandstone_normal.png", "red_sandstone.png");
        renamePairs.put("red_sandstone_carved.png", "chiseled_red_sandstone.png");
        renamePairs.put("red_sandstone_smooth.png", "cut_red_sandstone.png");
        renamePairs.put("wool_colored_black.png", "black_wool.png");
        renamePairs.put("wool_colored_blue.png", "blue_wool.png");
        renamePairs.put("wool_colored_brown.png", "brown_wool.png");
        renamePairs.put("wool_colored_cyan.png", "cyan_wool.png");
        renamePairs.put("wool_colored_gray.png", "gray_wool.png");
        renamePairs.put("wool_colored_green.png", "green_wool.png");
        renamePairs.put("wool_colored_light_blue.png", "light_blue_wool.png");
        renamePairs.put("wool_colored_lime.png", "lime_wool.png");
        renamePairs.put("wool_colored_magenta.png", "magenta_wool.png");
        renamePairs.put("wool_colored_orange.png", "orange_wool.png");
        renamePairs.put("wool_colored_pink.png", "pink_wool.png");
        renamePairs.put("wool_colored_purple.png", "purple_wool.png");
        renamePairs.put("wool_colored_red.png", "red_wool.png");
        renamePairs.put("wool_colored_silver.png", "light_gray_wool.png");
        renamePairs.put("wool_colored_white.png", "white_wool.png");
        renamePairs.put("wool_colored_yellow.png", "yellow_wool.png");
        renamePairs.put("stone_slab_side.png", "smooth_stone_slab_side.png");
        renamePairs.put("stone_slab_top.png", "smooth_stone.png");
        renamePairs.put("brick.png", "bricks.png");
        renamePairs.put("nether_brick.png", "nether_bricks.png");
        renamePairs.put("stonebrick.png", "stone_bricks.png");
        renamePairs.put("stonebrick_carved.png", "chiseled_stone_bricks.png");
        renamePairs.put("stonebrick_mossy.png", "mossy_stone_bricks.png");
        renamePairs.put("quartz_block_chiseled.png", "chiseled_quartz_block.png");
        renamePairs.put("quartz_block_lines.png", "quartz_pillar.png");
        renamePairs.put("quartz_block_lines_top.png", "quartz_pillar_top.png");
        renamePairs.put("prismarine_dark.png", "dark_prismarine.png");
        renamePairs.put("prismarine_rough.png", "prismarine.png");
        renamePairs.put("prismarine_rough.png.mcmeta", "prismarine.png.mcmeta");
        renamePairs.put("anvil_base.png", "anvil.png");
        renamePairs.put("anvil_top_damage_0.png", "anvil_top.png");
        renamePairs.put("anvil_top_damage_1.png", "chipped_anvil_top.png");
        renamePairs.put("anvil_top_damage_2.png", "damaged_anvil_top.png");
        renamePairs.put("carrots_stage_0.png", "carrots_stage0.png");
        renamePairs.put("carrots_stage_1.png", "carrots_stage1.png");
        renamePairs.put("carrots_stage_2.png", "carrots_stage2.png");
        renamePairs.put("carrots_stage_3.png", "carrots_stage3.png");
        renamePairs.put("cobblestone_mossy.png", "mossy_cobblestone.png");
        renamePairs.put("cocoa_stage_0.png", "cocoa_stage0.png");
        renamePairs.put("cocoa_stage_1.png", "cocoa_stage1.png");
        renamePairs.put("cocoa_stage_2.png", "cocoa_stage2.png");
        renamePairs.put("comparator_off.png", "comparator.png");
        renamePairs.put("deadbush.png", "dead_bush.png");
        renamePairs.put("dispenser_front_horizontal.png", "dispenser_horizontal.png");
        renamePairs.put("door_acacia_lower.png", "acacia_door_bottom.png");
        renamePairs.put("door_acacia_upper.png", "acacia_door_top.png");
        renamePairs.put("door_birch_lower.png", "birch_door_bottom.png");
        renamePairs.put("door_birch_upper.png", "birch_door_top.png");
        renamePairs.put("door_dark_oak_lower.png", "dark_oak_door_bottom.png");
        renamePairs.put("door_dark_oak_upper.png", "dark_oak_door_top.png");
        renamePairs.put("door_iron_lower.png", "iron_door_bottom.png");
        renamePairs.put("door_iron_upper.png", "iron_door_top.png");
        renamePairs.put("door_jungle_lower.png", "jungle_door_bottom.png");
        renamePairs.put("door_jungle_upper.png", "jungle_door_top.png");
        renamePairs.put("door_spruce_lower.png", "spruce_door_bottom.png");
        renamePairs.put("door_spruce_upper.png", "spruce_door_top.png");
        renamePairs.put("door_wood_lower.png", "oak_door_bottom.png");
        renamePairs.put("door_wood_upper.png", "oak_door_top.png");
        renamePairs.put("double_plant_fern_bottom.png", "large_fern_bottom.png");
        renamePairs.put("double_plant_fern_top.png", "large_fern_top.png");
        renamePairs.put("double_plant_grass_bottom.png", "tall_grass_bottom.png");
        renamePairs.put("double_plant_grass_top.png", "tall_grass_top.png");
        renamePairs.put("double_plant_paeonia_bottom.png", "peony_bottom.png");
        renamePairs.put("double_plant_paeonia_top.png", "peony_top.png");
        renamePairs.put("double_plant_rose_bottom.png", "rose_bush_bottom.png");
        renamePairs.put("double_plant_rose_top.png", "rose_bush_top.png");
        renamePairs.put("double_plant_sunflower_back.png", "sunflower_back.png");
        renamePairs.put("double_plant_sunflower_bottom.png", "sunflower_bottom.png");
        renamePairs.put("double_plant_sunflower_top.png", "sunflower_top.png");
        renamePairs.put("double_plant_sunflower_front.png", "sunflower_front.png");
        renamePairs.put("double_plant_syringa_bottom.png", "lilac_bottom.png");
        renamePairs.put("double_plant_syringa_top.png", "lilac_top.png");
        renamePairs.put("dropper_front_horizontal.png", "dropper_front.png");
        renamePairs.put("endframe_eye.png", "end_portal_frame_eye.png");
        renamePairs.put("endframe_side.png", "end_portal_frame_side.png");
        renamePairs.put("endframe_top.png", "end_portal_frame_top.png");
        renamePairs.put("farmland_dry.png", "farmland.png");
        renamePairs.put("farmland_wet.png", "farmland_moist.png");
        renamePairs.put("fire_layer_0.png", "fire_0.png");
        renamePairs.put("fire_layer_1.png", "fire_1.png");
        renamePairs.put("flower_allium.png", "allium.png");
        renamePairs.put("flower_blue_orchid.png", "blue_orchid.png");
        renamePairs.put("flower_dandelion.png", "dandelion.png");
        renamePairs.put("flower_houstonia.png", "azure_bluet.png");
        renamePairs.put("flower_oxeye_daisy.png", "oxeye_daisy.png");
        renamePairs.put("flower_rose.png", "poppy.png");
        renamePairs.put("flower_tulip_orange.png", "orange_tulip.png");
        renamePairs.put("flower_tulip_pink.png", "pink_tulip.png");
        renamePairs.put("flower_tulip_red.png", "red_tulip.png");
        renamePairs.put("flower_tulip_white.png", "white_tulip.png");
        renamePairs.put("furnace_front_off.png", "furnace_front.png");
        renamePairs.put("glass_black.png", "black_stained_glass.png");
        renamePairs.put("glass_blue.png", "blue_stained_glass.png");
        renamePairs.put("glass_brown.png", "brown_stained_glass.png");
        renamePairs.put("glass_cyan.png", "cyan_stained_glass.png");
        renamePairs.put("glass_gray.png", "gray_stained_glass.png");
        renamePairs.put("glass_green.png", "green_stained_glass.png");
        renamePairs.put("glass_light_blue.png", "light_blue_stained_glass.png");
        renamePairs.put("glass_lime.png", "lime_stained_glass.png");
        renamePairs.put("glass_magenta.png", "magenta_stained_glass.png");
        renamePairs.put("glass_orange.png", "orange_stained_glass.png");
        renamePairs.put("glass_pink.png", "pink_stained_glass.png");
        renamePairs.put("glass_purple.png", "purple_stained_glass.png");
        renamePairs.put("glass_red.png", "red_stained_glass.png");
        renamePairs.put("glass_silver.png", "light_gray_stained_glass.png");
        renamePairs.put("glass_white.png", "white_stained_glass.png");
        renamePairs.put("glass_yellow.png", "yellow_stained_glass.png");
        renamePairs.put("glass_pane_top_black.png", "black_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_blue.png", "blue_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_brown.png", "brown_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_cyan.png", "cyan_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_gray.png", "gray_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_green.png", "green_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_light_blue.png", "light_blue_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_lime.png", "lime_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_magenta.png", "magenta_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_orange.png", "orange_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_pink.png", "pink_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_purple.png", "purple_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_red.png", "red_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_silver.png", "light_gray_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_white.png", "white_stained_glass_pane_top.png");
        renamePairs.put("glass_pane_top_yellow.png", "yellow_stained_glass_pane_top.png");
        renamePairs.put("grass_side_overlay.png", "grass_block_side_overlay.png");
        renamePairs.put("grass_side_snowed.png", "grass_block_snow.png");
        renamePairs.put("hardened_clay.png", "terracotta.png");
        renamePairs.put("hardened_clay_stained_black.png", "black_terracotta.png");
        renamePairs.put("hardened_clay_stained_blue.png", "blue_terracotta.png");
        renamePairs.put("hardened_clay_stained_brown.png", "brown_terracotta.png");
        renamePairs.put("hardened_clay_stained_cyan.png", "cyan_terracotta.png");
        renamePairs.put("hardened_clay_stained_gray.png", "gray_terracotta.png");
        renamePairs.put("hardened_clay_stained_green.png", "green_terracotta.png");
        renamePairs.put("hardened_clay_stained_light_blue.png", "light_blue_terracotta.png");
        renamePairs.put("hardened_clay_stained_lime.png", "lime_terracotta.png");
        renamePairs.put("hardened_clay_stained_magenta.png", "magenta_terracotta.png");
        renamePairs.put("hardened_clay_stained_orange.png", "orange_terracotta.png");
        renamePairs.put("hardened_clay_stained_pink.png", "pink_terracotta.png");
        renamePairs.put("hardened_clay_stained_purple.png", "purple_terracotta.png");
        renamePairs.put("hardened_clay_stained_red.png", "red_terracotta.png");
        renamePairs.put("hardened_clay_stained_silver.png", "light_gray_terracotta.png");
        renamePairs.put("hardened_clay_stained_white.png", "white_terracotta.png");
        renamePairs.put("hardened_clay_stained_yellow.png", "yellow_terracotta.png");
        renamePairs.put("ice_packed.png", "packed_ice.png");
        renamePairs.put("itemframe_background.png", "item_frame.png");
        renamePairs.put("leaves_acacia.png", "acacia_leaves.png");
        renamePairs.put("leaves_big_oak.png", "dark_oak_leaves.png");
        renamePairs.put("leaves_birch.png", "birch_leaves.png");
        renamePairs.put("leaves_jungle.png", "jungle_leaves.png");
        renamePairs.put("leaves_oak.png", "oak_leaves.png");
        renamePairs.put("leaves_spruce.png", "spruce_leaves.png");
        renamePairs.put("melon_stem_connected.png", "attached_melon_stem.png");
        renamePairs.put("melon_stem_disconnected.png", "melon_stem.png");
        renamePairs.put("mob_spawner.png", "spawner.png");
        renamePairs.put("mushroom_block_skin_brown.png", "brown_mushroom_block.png");
        renamePairs.put("mushroom_block_skin_red.png", "red_mushroom_block.png");
        renamePairs.put("mushroom_block_skin_stem.png", "mushroom_stem.png");
        renamePairs.put("mushroom_brown.png", "brown_mushroom.png");
        renamePairs.put("mushroom_red.png", "red_mushroom.png");
        renamePairs.put("nether_wart_stage_0.png", "nether_wart_stage0.png");
        renamePairs.put("nether_wart_stage_1.png", "nether_wart_stage1.png");
        renamePairs.put("nether_wart_stage_2.png", "nether_wart_stage2.png");
        renamePairs.put("noteblock.png", "note_block.png");
        renamePairs.put("piston_top_normal.png", "piston_top.png");
        renamePairs.put("portal.png", "nether_portal.png");
        renamePairs.put("potatoes_stage_0.png", "potatoes_stage0.png");
        renamePairs.put("potatoes_stage_1.png", "potatoes_stage1.png");
        renamePairs.put("potatoes_stage_2.png", "potatoes_stage2.png");
        renamePairs.put("potatoes_stage_3.png", "potatoes_stage3.png");
        renamePairs.put("pumpkin_face_off.png", "carved_pumpkin.png");
        renamePairs.put("pumpkin_face_on.png", "jack_o_lantern.png");
        renamePairs.put("pumpkin_stem_connected.png", "attached_pumpkin_stem.png");
        renamePairs.put("pumpkin_stem_disconnected.png", "pumpkin_stem.png");
        renamePairs.put("rail_activator.png", "activator_rail.png");
        renamePairs.put("rail_activator_powered.png", "activator_rail_on.png");
        renamePairs.put("rail_detector.png", "detector_rail.png");
        renamePairs.put("rail_detector_powered.png", "detector_rail_on.png");
        renamePairs.put("rail_golden.png", "powered_rail.png");
        renamePairs.put("rail_golden_powered.png", "powered_rail_on.png");
        renamePairs.put("rail_normal.png", "rail.png");
        renamePairs.put("rail_normal_turned.png", "rail_corner.png");
        renamePairs.put("redstone_dust_cross_overlay.png", "redstone_dust_overlay.png");
        renamePairs.put("redstone_lamp_off.png", "redstone_lamp.png");
        renamePairs.put("redstone_torch_on.png", "redstone_torch.png");
        renamePairs.put("reeds.png", "sugar_cane.png");
        renamePairs.put("repeater_off.png", "repeater.png");
        renamePairs.put("sapling_acacia.png", "acacia_sapling.png");
        renamePairs.put("sapling_birch.png", "birch_sapling.png");
        renamePairs.put("sapling_jungle.png", "jungle_sapling.png");
        renamePairs.put("sapling_oak.png", "oak_sapling.png");
        renamePairs.put("sapling_roofed.png", "dark_oak_sapling.png");
        renamePairs.put("sapling_spruce.png", "spruce_sapling.png");
        renamePairs.put("slime.png", "slime_block.png");
        renamePairs.put("grass.png", "tall_grass.png");
        renamePairs.put("torch_on.png", "torch.png");
        renamePairs.put("trapdoor.png", "oak_trapdoor.png");
        renamePairs.put("trip_wire_source.png", "tripwire_hook.png");
        renamePairs.put("waterlily.png", "lily_pad.png");
        renamePairs.put("web.png", "cobweb.png");
        renamePairs.put("wheat_stage_0.png", "wheat_stage0.png");
        renamePairs.put("wheat_stage_1.png", "wheat_stage1.png");
        renamePairs.put("wheat_stage_2.png", "wheat_stage2.png");
        renamePairs.put("wheat_stage_3.png", "wheat_stage3.png");
        renamePairs.put("wheat_stage_4.png", "wheat_stage4.png");
        renamePairs.put("wheat_stage_5.png", "wheat_stage5.png");
        renamePairs.put("wheat_stage_6.png", "wheat_stage6.png");
        renamePairs.put("wheat_stage_7.png", "wheat_stage7.png");
    }

    @Override
    public void transform(File inDir, File outDir, HashMap<String, Boolean> processed) throws IOException {
        Path oldBlocksPath = Path.of("assets", "minecraft", "textures", "blocks");
        Path newBlocksPath = Path.of("assets", "minecraft", "textures", "block");

        // first, copy the old blocks directory to the new blocks directory
        Path sourcePath = inDir.toPath().resolve(oldBlocksPath);
        Path destPath = outDir.toPath().resolve(newBlocksPath);
        Files.createDirectories(destPath);
        Files.walkFileTree(sourcePath, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                Path targetFile = destPath.resolve(renamePairs.getOrDefault(file.getFileName().toString(), file.getFileName().toString()));
                Files.copy(file, targetFile, StandardCopyOption.REPLACE_EXISTING);
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
                Path targetDir = destPath.resolve(sourcePath.relativize(dir));
                Files.createDirectories(targetDir);
                return FileVisitResult.CONTINUE;
            }
        });

        for (var entry : processed.entrySet()) {
            if (Path.of(entry.getKey()).startsWith(oldBlocksPath)) {
                System.out.println("blocks transformer: " + entry.getKey() + ":" + entry.getValue());
                entry.setValue(true);
            }
        }
    }
}
